### PR TITLE
allow installation with Symfony3

### PR DESCRIPTION
**Pull request by benji07**
https://github.com/minkphp/MinkBrowserKitDriver/pull/102 should be merged before this one

### CODE REVIEW

**Comment by benji07** [comment]
ping @stof, the test pass (2 failed with a memory limit exception)

**Comment by benji07** [comment]
@everzet this PR is ready to be merged (as minkphp/MinkBrowserKitDriver#102 was merged last week)

**Comment by mmoreram** [comment]
:+1:

**Comment by mmoreram** [comment]
@everzet can you merge please?

**Comment by riskawarrior** [comment]
:+1: Merge please

**Comment by acasademont** [comment]
+1

**Comment by tyx** [comment]
:+1:

**Comment by maximecolin** [comment]
:+1:

**Comment by rgomezcasas** [comment]
Hey, do you need help here?

**Comment by emiliomg** [comment]
It would be absolutely great if this PR would be merged asap, but somehow I think this won't happen this year anymore, at least not today ;-)

**Comment by robholmes** [comment]
:+1: for me too. We really need this merging as soon as possible. The builds are failing due to a memory issue running composer. I don't know how I can help with this, but if someone can fix the build then maybe it will be merged.

**Comment by dosten** [comment]
:+1: but the extension name make no sense anymore, should be SymfonyExtension IMO

**Comment by novacp** [comment]
Are there any news? Behat + Symfony3 can't be used currently, installation of Symfony3 fails "behat/symfony2-extension v2.1.0 requires symfony/framework-bundle ~2.0"

**Comment by scaytrase** [comment]
ping @stof @everzet

**Comment by diegomarangoni** [comment]
With Symfony 3 support project and package name make no sense anymore.

What if rename to:
https://packagist.org/packages/behat/symfony-extension
https://github.com/Behat/SymfonyExtension

**Comment by scaytrase** [comment]
@diegomarangoni there is no sense in "2" since [Symfony2 renamed to Symfony](https://github.com/symfony/symfony/pull/12565)

**Comment by sroze** [comment]
@everzet FYI, the 2 travis failures are because of a PHP _Allowed memory size [...]_ error caused by Composer.

**Comment by everzet** [comment]
@sroze thanks for heads-up

**Comment by everzet** [comment]
@benji07 Thank you very much for contribution!

**Comment by Ma27** [comment]
when will the release come? ;)

**Comment by sroze** [comment]
@Ma27 that's released as [2.1.1](https://github.com/Behat/Symfony2Extension/releases/tag/2.1.1).

**Comment by Ma27** [comment]
:+1:

**Pull request merged**
