### PR TITLE
Support symfony 5

### PR DESCRIPTION
**Pull request by gabfr**
I know there is already the PR #152 to add support for symfony v5, but it seems abadoned, and since I'm in need I did this PR with mine and @larzuk91 commits, also with some modifications suggested in the #152 discussions too.

### CODE REVIEW

**Comment by gabfr** [comment]
It seems that we'll have to wait for `behat/behat` support of symfony v5 components, moreover, the merge of this PR (https://github.com/Behat/Behat/pull/1256) .

**Comment by piotrbrzezina** [comment]
any news about this PR ?

**Comment by gabfr** [comment]
I ended up not using this extension anymore in my project. It’s quite simple to remove its usage.

I can’t disclosure the source of my project, but if you need any help, just reach me on my email or linkedin.

**Comment by alexander-schranz** [comment]
@gabfr do you maybe have some gist where you did remove the extension. I'm sadly not familiar with behat and try to update a [bundle](https://github.com/massiveart/MassiveSearchBundle/pull/134) which currently use it.

**Comment by verschoof** [comment]
https://github.com/Behat/Behat/pull/1256 has been merged, can you rerun the tests?

**Comment by gabfr** [comment]
@verschoof sorry, It seems we have a problem with the PHPUnit version. I'm in a hurry now. I'll take some time to look into it.

@alexander-schranz sure. I'll do a gist with the changes asap!

**Comment by alexander-schranz** [comment]
@gabfr would be great if you could provide a gist. I will have a look at the PHPUnit version problem!

**Comment by gabfr** [comment]
@alexander-schranz here you are: https://gist.github.com/gabfr/65cbfedefe7dbfcbc9606677acb437d9

**Comment by alexander-schranz** [comment]
@gabfr Thank you did work for me! The changes I needed to do can be found here maybe it helps somebody: https://github.com/massiveart/MassiveSearchBundle/pull/139/files

**Pull request closed without merging**
